user feedback syntax

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -22,8 +22,9 @@ jobs:
       - uses: isort/isort-action@v1
       - name: User feedback
         if: ${{ failure() }}
-        run: echo "::error::Run 'python.exe -m isort .' and commit changes to fix errors."      
-
+        run: |
+            echo "::error::Run 'python.exe -m isort .' and commit changes to fix errors."
+            exit 1
   CI_Testing:
     strategy:
       max-parallel: 4
